version: '3'

services:
  server:
    build: ./src
    environment:
      SQL_HOST: ${POSTGRES_HOST}
      SQL_PORT: ${POSTGRES_PORT}
      SQL_USER: ${POSTGRES_USER}
      SQL_PASSWORD: ${POSTGRES_PASSWORD}
      SQL_DB: ${POSTGRES_DB}
      API_PORT: ${API_PORT}
    ports:
      - 8080:8080
    networks:
      - postgres_net
    depends_on:
      - postgres
    restart: on-failure

  postgres:
    image: postgres:9.6.17
    volumes:
      - ./data/pgsql:/var/lib/postgresql/data
#      - pgsql:/var/lib/postgresql/data
#      - pgconf:/etc/postgresql
#      - pglog:/var/log/postgresql
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - postgres_net
    container_name: postgres

#volumes:
#  pgsql:
#    driver: local
#  pgconf:
#    driver: local
#  pglog:
#    driver: local

networks:
  postgres_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 11.0.9.0/24
